---
## The command is then:
## ansible-playbook -vv -i oicr-inventory.ini --connection=ssh --become-method=sudo --extra-vars=import_directory=/... import.yml

- hosts: application
  tasks:
    - name: 'setup'
      setup:
        filter: '*'

- hosts: application
  tasks:
    - name: Local variables
      include_vars: "{{ item }}"
      with_first_found:
        - "vars/local_config_{{app_profile}}.yml"
        - "vars/{{ansible_os_family|lower}}.yml"
        - "vars/defaults.yml"

- hosts: application
  become: true
  roles:
    - { role: import, tags: [ 'import' ] }
