---

- name: cBioPortal import | clear out old import data
  file:
    state: directory
    path: "{{remote_staging}}"

- name: cBioPortal import | clear out old import data
  command: rm -rf "{{remote_staging}}/*"

# We might fail here if we don't have a directory of data
- name: cBioPortal import | copy over staging data
  copy:
    src: "{{import_directory}}/"
    dest: "{{remote_staging}}/"

- name: cBioPortal import | import the data
  shell: >
    env PORTAL_HOME={{webapp_directory}} java -cp scripts-`cat version`.jar -jar cbioportal-importer-`cat importer-version`.jar {{remote_staging}} cbioportal-import.xml
    chdir="{{webapp_directory}}"
